name = "safepup"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
